import type { Metadata } from "next";
import { Geist, Instrument_Serif, Meow_Script } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const instrumentSerif = Instrument_Serif({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-instrument-serif",
});

const meowScript = Meow_Script({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-meow-script",
});

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="de"
      className={`${instrumentSerif.variable} ${meowScript.variable} ${geist.variable} h-full scroll-smooth antialiased`}
    >
      <body className="relative flex min-h-full flex-col overflow-x-hidden">
        <Image
          src="/eucalyptus-top-right-cropped.png"
          width={500}
          height={500}
          alt="Eucalyptus"
          className="absolute -top-72 -right-44 w-auto sm:-top-44 sm:-right-16"
          loading="eager"
          draggable={false}
        />
        <main className="space-y-4 sm:space-y-24">{children}</main>
        <footer className="relative overflow-hidden pt-16 pb-10 text-center">
          <Image
            src="/eucalyptus-bottom-left-cropped.png"
            width={500}
            height={500}
            alt="Eucalyptus"
            className="absolute -bottom-72 -left-44 w-auto"
            draggable={false}
          />
          Wir freuen uns auf euch
        </footer>
      </body>
    </html>
  );
}
